<a href="https://colab.research.google.com/github/ecepiskin/Final-Project-2/blob/main/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:


pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
import numpy as np

In [3]:
import pandas
df = pandas.read_excel('semadeneme.xlsx')

In [4]:
print (df.columns)

Index(['SEMA M', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21'],
      dtype='object')

In [5]:
print(df.describe())

         SEMA M Unnamed: 1      Unnamed: 2     Unnamed: 3 Unnamed: 4  \
count         9          8               6              1          1
unique        9          2               6              1          1
top     AVERAGE     Anchor  STEAMING HOURS  Average Speed   Slip (%)
freq          1          7               1              1          1

        Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8 Unnamed: 9  ...  \
count            9         8.0         9.0           8          9  ...
unique           9         7.0         3.0           2          9  ...
top     VLSFO\nROB        -3.2       213.8           0   FW \nROB  ...
freq             1         2.0         7.0           7          1  ...

        Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  \
count             8            9            8            9            8
unique            4            5            5            8            7
top               0          693            0           90           10
freq              5            3            4            2            2

        Unnamed: 17  Unnamed: 18  Unnamed: 19  Unnamed: 20 Unnamed: 21
count             9            8            8            1           1
unique            4            4            8            1           1
top            2746            0   Engine RPM  Engine Load    TC \nRPM
freq              4            5            1            1           1

[4 rows x 22 columns]

In [6]:
df.head()

,SEMA M,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,REPORT\nTYPE,STEAMING HOURS,Average Speed,Slip (%),VLSFO\nROB,VLSFO Cons.,MGO \nROB,MGO \nCons.,FW \nROB,...,M/E System Lub Oil Cons.,D/G Lub Oil \nROB,D/G Lub Oil \nCons.,M/E Cylinder Oil \nROB,M/E Cylinder Oil \nCons.,Hyd Oil\nROB,Hyd Oil Cons.,Engine RPM,Engine Load,TC \nRPM
1,AVERAGE,NaN,NaN,NaN,NaN,740.378571,-1.666667,213.8,0,96.142857,...,166.666667,685.285714,8.333333,94.285714,14.166667,2703.142857,16.666667,NaN,NaN,NaN
2,DATE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01.11.2024,Anchor,12,NaN,NaN,750.2,4.45,213.8,0,114,...,0,717,24,150,40,2746,0,78,NaN,NaN
4,02.11.2024,Anchor,18.2,NaN,NaN,745.75,-3.05,213.8,0,108,...,0,693,0,110,20,2746,0,75,NaN,NaN

In [8]:
df.columns = ['SEMA_M', 'Steaming Hrs', 'REPORT_TYPE', 'Average_Speed', 'Slip', 'VLFO ROB', 'VLSFO Cons.', 'MGO ROB', 'MGO Cons.', 'FW ROB', 'FW Cons.', 'M/E System Lub Oil ROB', 'M/E System Lub Oil Cons' , 'M/E Cylinder Oil ROB', 'M/E Cylinder Oil Cons' ,'D/G Lub Oil ROB', 'D/G Lub Oil Cons', 'Hyd Oil ROB' , 'Hyd Oil Cons' , 'Engine RPM' , 'Engine Load','TC RPM']

In [9]:
df.head()

,SEMA_M,Steaming Hrs,REPORT_TYPE,Average_Speed,Slip,VLFO ROB,VLSFO Cons.,MGO ROB,MGO Cons.,FW ROB,...,M/E System Lub Oil Cons,M/E Cylinder Oil ROB,M/E Cylinder Oil Cons,D/G Lub Oil ROB,D/G Lub Oil Cons,Hyd Oil ROB,Hyd Oil Cons,Engine RPM,Engine Load,TC RPM
0,NaN,REPORT\nTYPE,STEAMING HOURS,Average Speed,Slip (%),VLSFO\nROB,VLSFO Cons.,MGO \nROB,MGO \nCons.,FW \nROB,...,M/E System Lub Oil Cons.,D/G Lub Oil \nROB,D/G Lub Oil \nCons.,M/E Cylinder Oil \nROB,M/E Cylinder Oil \nCons.,Hyd Oil\nROB,Hyd Oil Cons.,Engine RPM,Engine Load,TC \nRPM
1,AVERAGE,NaN,NaN,NaN,NaN,740.378571,-1.666667,213.8,0,96.142857,...,166.666667,685.285714,8.333333,94.285714,14.166667,2703.142857,16.666667,NaN,NaN,NaN
2,DATE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01.11.2024,Anchor,12,NaN,NaN,750.2,4.45,213.8,0,114,...,0,717,24,150,40,2746,0,78,NaN,NaN
4,02.11.2024,Anchor,18.2,NaN,NaN,745.75,-3.05,213.8,0,108,...,0,693,0,110,20,2746,0,75,NaN,NaN

In [14]:
import pandas as pd

# Convert 'Engine RPM' to numeric (if it's not already)
df['Engine RPM'] = pd.to_numeric(df['Engine RPM'], errors='coerce')  # 'coerce' will turn invalid parsing into NaN

# Filter data based on 'Engine RPM' ranges and calculate the average of 'M/E Cylinder Oil Cons'
def calculate_avg_cylinder_oil(df):
    # RPM Range 70-75
    rpm_70_75 = df[(df['Engine RPM'] >= 70) & (df['Engine RPM'] < 75)]
    avg_70_75 = rpm_70_75['M/E Cylinder Oil Cons'].mean()

    # RPM Range 75-80
    rpm_75_80 = df[(df['Engine RPM'] >= 75) & (df['Engine RPM'] < 80)]
    avg_75_80 = rpm_75_80['M/E Cylinder Oil Cons'].mean()

    # RPM Range 80-85
    rpm_80_85 = df[(df['Engine RPM'] >= 80) & (df['Engine RPM'] < 85)]
    avg_80_85 = rpm_80_85['M/E Cylinder Oil Cons'].mean()

    # Returning results as a dictionary
    return {
        'Average M/E Cylinder Oil Cons (RPM 70-75)': avg_70_75,
        'Average M/E Cylinder Oil Cons (RPM 75-80)': avg_75_80,
        'Average M/E Cylinder Oil Cons (RPM 80-85)': avg_80_85
    }

# Example of how to use this function
result = calculate_avg_cylinder_oil(df)
print(result)

{'Average M/E Cylinder Oil Cons (RPM 70-75)': nan, 'Average M/E Cylinder Oil Cons (RPM 75-80)': 12.0, 'Average M/E Cylinder Oil Cons (RPM 80-85)': 0.0}

In [13]:
import pandas as pd

# Assuming you have already loaded your DataFrame (df) from an Excel file
# df = pd.read_excel('your_file_path.xlsx')  # Uncomment and replace with your file path

# Convert 'Engine RPM' to numeric (if it's not already)
df['Engine RPM'] = pd.to_numeric(df['Engine RPM'], errors='coerce')  # 'coerce' will turn invalid parsing into NaN

# Filter data based on 'Engine RPM' ranges and calculate the average of 'M/E Cylinder Oil Cons'
def calculate_avg_cylinder_oil(df):
    # RPM Range 70-75
    rpm_70_75 = df[(df['Engine RPM'] >= 70) & (df['Engine RPM'] < 75)]
    avg_70_75 = rpm_70_75['VLSFO Cons.'].mean()

    # RPM Range 75-80
    rpm_75_80 = df[(df['Engine RPM'] >= 75) & (df['Engine RPM'] < 80)]
    avg_75_80 = rpm_75_80['VLSFO Cons.'].mean()

    # RPM Range 80-85
    rpm_80_85 = df[(df['Engine RPM'] >= 80) & (df['Engine RPM'] < 85)]
    avg_80_85 = rpm_80_85['VLSFO Cons.'].mean()

    # Returning results as a dictionary
    return {
        'VLSFO Cons. (RPM 70-75)': avg_70_75,
        'VLSFO Cons. (RPM 75-80)': avg_75_80,
        'VLSFO Cons. (RPM 80-85)': avg_80_85
    }

# Example of how to use this function
result = calculate_avg_cylinder_oil(df)
print(result)

{'VLSFO Cons. (RPM 70-75)': nan, 'VLSFO Cons. (RPM 75-80)': 0.7000000000000455, 'VLSFO Cons. (RPM 80-85)': -3.2000000000000455}